apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: app
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: python
        image: francistor/python.app:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: test
spec:
  ingressClassName: cloud-provider-kind
  rules:
  - http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: app
            port:
              number: 5000