name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Where are we
        shell: bash
        run: |
          pwd 
          ls
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Shorten commit id
        shell: bash 
        run: |
          echo COMMIT_ID="${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: francistor/python.app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    runs-on: local-kind
    needs: ci
    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Get commit id
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}
          # VERSION=v4.2.0
          # PLATFORM=linux_amd64
          # curl -Ls https://github.com/mikefarah/yq/releases/download/${VERSION}/yq_${PLATFORM}.tar.gz | tar xz && sudo mv yq_${PLATFORM} /usr/local/bin/yq
          # yq -i '.image.tag = "'"${{ needs.ci.outputs.commit_id }}"'"' charts/values.yaml
          sed -i "s/.*tag:.*/  tag: ${{ needs.ci.outputs.commit_id }}/" charts/python-app/values.yaml

      - name: commit to github 
        uses: EndBug/add-and-commit@v9
        with:
          author_name: francistor
          autor_email: francisco.cardosogil@gmail.com
          message: update tag

      - name: Deploy to argocd
        shell: bash 
        run: |
          argocd login argocd-server.argocd --insecure --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app